# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
#port: 3000
safe: true

# edit here to achieve your personal greatness
url: http://dotps1.github.io/WinSCP
baseurl: ""
title: WinSCP
author: Thomas Malkewitz
description: WinSCP PowerShell Wrapper Module.
#disqus: username
#google_analytics: UA-69391421-1