highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
#port: 3000
safe: true

# Prod
url: http://dotps1.github.io/WinSCP
# Dev
#url: http://localhost:4000
baseurl: ""
title: WinSCP
author: Thomas Malkewitz
description: WinSCP PowerShell Wrapper Module.
#disqus: username
#google_analytics: